### PR TITLE
I implemented the footer design with working icons and a placeholder …

### PR DESCRIPTION
**Pull request by AvaneeshM**
I implemented the footer design with working icons and a placeholder logo as the final logo has yet to be made

### CODE REVIEW

**Comment by CoderHahs** [comment]
Could you add a picture in the comments just so I can see how it looks. Thanks

**Comment by AvaneeshM** [comment]
Here is the picture:
PlaceHolder-Logo

**Comment by AvaneeshM** [comment]
image

**Comment by CoderHahs** [comment]
Is it possible to have the media icons grouped together, so beside each other on the left, and the logo on right. Also, have them all aligned with the header at the top. They should be vertically aligned.

**Pull request merged**
